config/routes.rb
Rails.application.routes.draw do
  root "appointments#index"

  resources :appointments, :doctors, :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validates :issue, :date, :start_time, :end_time, :doctor_id, :patient_id, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  validates :name, :specialty, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  validates :name, :dob, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
  	@appointments = Appointment.all
  end

  def show
  	@appointment = Appointment.find(params[:id])
  end

  def create
  	@appointment = Appointment.new(appointment_params)

  	if @appointment.save
  	  redirect_to root_path, notice: "Appointment successfully scheduled!"
  	else
  	  redirect_to root_path, alert: "Invalid input, appointment scheduling failed..."
  	end
  end

  def edit
  	@appointment = Appointment.find(params[:id])
  end

  def update
  	@appointment = Appointment.find(params[:id])

  	if @appointment.update(appointment_params)
  	  redirect_to @appointment, notice: "Appointment successfully updated!"
  	else
  	  flash.now[:alert] = "Invalid input, appointment update failed..."
      render :edit
    end
  end

  def destroy
  	@appointment = Appointment.find(params[:id])
  	@appointment.destroy

  	redirect_to root_path, notice: "Appointment successfully deleted!"
  end

  private
  	def appointment_params
  	  params.require(:appointment).permit(:issue, :date, :start_time, :end_time, :patient_id, :doctor_id)
  	end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to doctors_path, notice: "Doctor profile successfully created!"
    else
      redirect_to doctors_path, alert: "Invalid input, Doctor profile creation failed..."
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])

    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: "Doctor profile successfully updated!"
    else
      flash.now[:alert] = "Invalid input, Doctor profile update failed..."
      render :edit
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    redirect_to doctors_path, notice: "Doctor profile successfully deleted!"
  end

  private
  	def doctor_params
  	  params.require(:doctor).permit(:name, :specialty)
  	end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to patients_path, notice: "Patient profile successfully created!"
    else
      redirect_to patients_path, alert: "Invalid input, patient profile creation failed..."
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to @patient, notice: "Patient profile successfully updated!"
    else
      flash.now[:alert] = "Invalid input, patient profile update failed..."
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to patients_path, notice: "Patient profile successfully deleted!"
  end

  private
  	def patient_params
  	  params.require(:patient).permit(:name, :dob, :is_insured)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%# Create a form for appointment that has placeholders %>
<%= form_with model: appointment do |form| %>
  <div class="form-group mb-3">
    <div class="row g-2">
      <div class="col">
        <%= form.collection_select :patient_id, Patient.all, :id, :name, {prompt: "Select Patient"}, {class: "form-select mb-2"} %>
      </div>
      <div class="col">
        <%= form.collection_select :doctor_id, Doctor.all, :id, :name, {prompt: "Select Doctor"}, {class: "form-select mb-2"} %>
      </div>
    </div>
    <div class="row g-2">
      <div class="col input-group mb-2">
        <span class="input-group-text">Date</span>
        <%= form.date_field :date, class: "form-control" %>
      </div>
      <div class="col input-group mb-2">
        <span class="input-group-text">Start Time</span>
        <%= form.time_field :start_time, class: "form-control" %>
      </div>
      <div class="col input-group mb-2">
        <span class="input-group-text">End Time</span>
        <%= form.time_field :end_time, class: "form-control" %>
      </div>
    </div>
    <%= form.text_area :issue, class: "form-control", placeholder: "Describe issue", rows: "5" %>
  </div>

  <div class="form-group ms-2">
    <%= form.submit "Submit", class: "btn btn-secondary mb-3" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<%# Render the new/edit appointment form in a card %>
<div class="card w-100 mx-auto mt-5 mb-3 text-dark bg-light">
  <div class="card-header">
  	<p class="card-text text-center fs-4">Edit Appointment</p>
  </div>
  <div class="card-body">
    <%= render "form", appointment: @appointment %>
  </div>
</div>

<%# Add a back button that redirects back to the show view for the appointment %>
<div class="container mb-5 text-center">
  <%= link_to "Back", @appointment, class: 'btn btn-dark px-5' %>
</div>

app/views/appointments/index.html.erb
<%# Check if there are any appointments %>
<% if @appointments.empty? %>
  <%# If the appointments array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto mb-5 mt-3">
    <div class="card-header text-center">
      <p class="card-text">No appointments scheduled...</p>
    </div>
  </div>
<% else %>
  <%# Otherwise, list all appointments as clickable links %>
  <div class="card bg-light mb-5 mt-3">
    <div class="card-header text-center">
      Scheduled Appointments
    </div>
    <div class="card-body">
      <ul class="list-group">
        <%# Goes thru each appointment and creates a clickable list-group-item link %>
        <% @appointments.each_with_index do |appointment, i| %>
          <%= link_to ((i + 1).to_s + " : " + appointment.doctor.name + " => " + appointment.patient.name), appointment, class: "list-group-item list-group-item-action list-group-item-light" %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="card bg-light mb-3">
  <div class="card-header text-center">
  	New Appointment
  </div>
  <div class="card-body">
    <%= render "form", appointment: Appointment.new %>
  </div>
</div>

app/views/appointments/show.html.erb
<%# Display the appt and give the option to edit and delete it %>
<div class="card w-100 mt-5 mb-5 mx-auto text-dark bg-light">
  <div class="card-header fs-5 fw-bold py-3 text-center">
  	Appointment Details
  </div>
  <div class="card-body mb-1">
    <dl class="row">
      <dt class="col-sm-2 text-nowrap">Patient:</dt>
      <dd class="col-sm-10"><%= link_to @appointment.patient.name, @appointment.patient, class: 'btn btn-sm btn-outline-secondary' %></dd>
      <dt class="col-sm-2 text-nowrap">Doctor:</dt>
      <dd class="col-sm-10"><%= link_to @appointment.doctor.name, @appointment.doctor, class: 'btn btn-sm btn-outline-secondary' %></dd>
      <dt class="col-sm-2 text-nowrap">Date:</dt>
      <dd class="col-sm-10"><%= @appointment.date.strftime("%m/%d/%Y") %></dd>
      <dt class="col-sm-2 text-nowrap">Start Time:</dt>
      <dd class="col-sm-10"><%= @appointment.start_time.to_formatted_s(:time) %></dd>
      <dt class="col-sm-2 text-nowrap">End Time:</dt>
      <dd class="col-sm-10"><%= @appointment.end_time.to_formatted_s(:time) %></dd>
    </dl>
    <div class="card mb-2">
      <div class="card-header">
        Issue Description:
      </div>
      <div class="card-body">
        <p class="card-title"><%= simple_format(@appointment.issue) %></p>
      </div>
    </div>
    <div class="ms-2">
	  <%= link_to "Edit", edit_appointment_path(@appointment), class: 'btn btn-secondary px-4 mx-1' %>
	  <%= link_to "Delete", appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger mx-1' %>
	</div>
  </div>
</div>

app/views/doctors/_form.html.erb
<%# Create a form for doctor that has placeholders %>
<%= form_with model: doctor do |form| %>
  <div class="form-group mb-3">
    <%= form.text_field :name, class: "form-control mb-2", placeholder: "Name" %>
    <%= form.text_field :specialty, class: "form-control", placeholder: "Specialty" %>
  </div>

  <div class="form-group ms-2">
    <%= form.submit "Submit", class: "btn btn-secondary mb-3" %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<%# Render the new/edit doctor form in a card %>
<div class="card w-100 mx-auto mt-5 mb-3 text-dark bg-light">
  <div class="card-header">
  	<p class="card-text text-center fs-4">Edit Doctor Profile</p>
  </div>
  <div class="card-body">
    <%= render "form", doctor: @doctor %>
  </div>
</div>

<%# Add a back button that redirects back to the show view for the doctor %>
<div class="container mb-5 text-center">
  <%= link_to "Back", @doctor, class: 'btn btn-dark px-5' %>
</div>

app/views/doctors/index.html.erb
<%# Check if there are any doctors %>
<% if @doctors.empty? %>
  <%# If the doctors array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto mb-5 mt-3">
    <div class="card-header text-center">
      <p class="card-text">No doctors added...</p>
    </div>
  </div>
<% else %>
  <%# Otherwise, list all doctors as clickable links %>
  <div class="card bg-light mb-5 mt-3">
    <div class="card-header text-center">
      Current Doctors
    </div>
    <div class="card-body">
      <ul class="list-group">
        <% @doctors.each do |doctor| %>
          <%= link_to doctor.name, doctor, class: "list-group-item list-group-item-action list-group-item-light" %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="card bg-light mb-3">
  <div class="card-header text-center">
  	Add Doctor
  </div>
  <div class="card-body">
    <%= render "form", doctor: Doctor.new %>
  </div>
</div>

app/views/doctors/show.html.erb
<%# Display the doctor and give the option to edit and delete it %>
<div class="card w-100 mt-5 mb-5 mx-auto text-dark bg-light">
  <div class="card-header fs-5 fw-bold py-3">
  	<%= @doctor.name %>
  </div>
  <div class="card-body mb-1">
    <dl class="row">
      <dt class="col-sm-2 text-nowrap">Specialty:</dt>
      <dd class="col-sm-10"><%= @doctor.specialty %></dd>
    </dl>
    <div class="ms-2">
	  <%= link_to "Edit", edit_doctor_path(@doctor), class: 'btn btn-secondary px-4 mx-1' %>
	  <%= link_to "Delete", doctor_path(@doctor), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger mx-1' %>
	</div>
  </div>
</div>

<%# Check if there are any appointments %>
<% if @doctor.appointments.empty? %>
  <%# If the appointments array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto mb-5">
    <div class="card-header text-center">
      <p class="card-text">No appointments scheduled...</p>
    </div>
  </div>
<% else %>
  <%# Otherwise, list all appointments as clickable links %>
  <div class="card bg-light mb-5">
    <div class="card-header text-center">
      Scheduled Appointments
    </div>
    <div class="card-body">
      <ul class="list-group">
        <% @doctor.appointments.each_with_index do |appointment, i| %>
          <%= link_to ((i + 1).to_s + " : " + appointment.date.strftime("%m/%d/%Y") + " => " + appointment.patient.name), appointment, class: "list-group-item list-group-item-action list-group-item-light" %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<%# Styles alert with bootstrap and make it red to signify an error %>
<div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #453f3d;">
  <div class="container-fluid">
    <%= link_to 'Rails Hospital App', appointments_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to 'Appointments', appointments_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Doctors', doctors_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Patients', patients_path, class:'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<%# Styles notice with bootstrap and make it green to signify success %>
<div class="alert alert-success alert-dismissible fade show mt-2" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Rails-Hospital-App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Render header partial above all pages -->
    <%= render 'layouts/header' %>
    <!-- Put contents in a bootstrap container -->
    <div class="container">
      <!-- If any notices or alerts are sent, render them with corresponding partial -->
      <% if notice %>
        <%= render 'layouts/notices' %>
      <% end %>
      <% if alert %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Bootstrap script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/patients/_form.html.erb
<%# Create a form for doctor that has placeholders %>
<%= form_with model: patient do |form| %>
  <div class="form-group mb-3">
    <%= form.text_field :name, class: "form-control mb-2", placeholder: "Name" %>
    <div class="input-group mb-2">
      <span class="input-group-text">Date of Birth</span>
	  <%= form.date_field :dob, class: "form-control" %>
	</div>
    <div class="form-check pt-1">
      <%= form.check_box :is_insured, {class: "form-check-input"} %>
      <%= form.label :is_insured, "Patient Insured?", class: "form-check-label" %>
    </div>
  </div>

  <div class="form-group ms-2">
    <%= form.submit "Submit", class: "btn btn-secondary mb-3" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<%# Render the new/edit patient form in a card %>
<div class="card w-100 mx-auto mt-5 mb-3 text-dark bg-light">
  <div class="card-header">
  	<p class="card-text text-center fs-4">Edit Patient Profile</p>
  </div>
  <div class="card-body">
    <%= render "form", patient: @patient %>
  </div>
</div>

<%# Add a back button that redirects back to the show view for the patient %>
<div class="container mb-5 text-center">
  <%= link_to "Back", @patient, class: 'btn btn-dark px-5' %>
</div>

app/views/patients/index.html.erb
<%# Check if there are any patients %>
<% if @patients.empty? %>
  <%# If the patients array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto mb-5 mt-3">
    <div class="card-header text-center">
      <p class="card-text">No patients added...</p>
    </div>
  </div>
<% else %>
  <%# Otherwise, list all patients as clickable links %>
  <div class="card bg-light mb-5 mt-3">
    <div class="card-header text-center">
      Current Patients
    </div>
    <div class="card-body">
      <ul class="list-group">
        <% @patients.each do |patient| %>
          <%= link_to patient.name, patient, class: "list-group-item list-group-item-action list-group-item-light" %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="card bg-light mb-3">
  <div class="card-header text-center">
  	Add Patient
  </div>
  <div class="card-body">
    <%= render "form", patient: Patient.new %>
  </div>
</div>

app/views/patients/show.html.erb
<%# Display the patient and give the option to edit and delete it %>
<div class="card w-100 mt-5 mb-5 mx-auto text-dark bg-light">
  <div class="card-header fs-5 fw-bold py-3">
  	<%= @patient.name %>
  </div>
  <div class="card-body mb-1">
    <dl class="row">
      <dt class="col-sm-2 text-nowrap">Date of Birth:</dt>
      <dd class="col-sm-10"><%= @patient.dob.strftime("%m/%d/%Y") %></dd>
      <dt class="col-sm-2 text-nowrap">Insured:</dt>
      <dd class="col-sm-10 text-capitalize"><%= @patient.is_insured.nil? ? "false" : @patient.is_insured %></dd>
    </dl>
    <div class="ms-2">
	  <%= link_to "Edit", edit_patient_path(@patient), class: 'btn btn-secondary px-4 mx-1' %>
	  <%= link_to "Delete", patient_path(@patient), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger mx-1' %>
	</div>
  </div>
</div>

<%# Check if there are any appointments %>
<% if @patient.appointments.empty? %>
  <%# If the appointments array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto mb-5">
    <div class="card-header text-center">
      <p class="card-text">No appointments scheduled...</p>
    </div>
  </div>
<% else %>
  <%# Otherwise, list all appointments as clickable links %>
  <div class="card bg-light mb-5">
    <div class="card-header text-center">
      Scheduled Appointments
    </div>
    <div class="card-body">
      <ul class="list-group">
        <% @patient.appointments.each_with_index do |appointment,i| %>
          <%= link_to ((i + 1).to_s + " : " + appointment.date.strftime("%m/%d/%Y") + " => " + appointment.doctor.name), appointment, class: "list-group-item list-group-item-action list-group-item-light" %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>